# Generated by Django 3.0.7 on 2020-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('unvan', models.CharField(max_length=150, verbose_name='Unvan')),
                ('zzip', models.CharField(max_length=10, verbose_name='ZIP')),
                ('tel', models.CharField(max_length=15, verbose_name='TEL')),
                ('fax', models.CharField(max_length=40, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('parol', models.CharField(max_length=40, verbose_name='Password')),
                ('wep', models.CharField(max_length=40, verbose_name='wep')),
                ('dogumTarixi', models.CharField(max_length=40, verbose_name='bornDate')),
            ],
        ),
    ]
