# Generated by Django 3.0.7 on 2020-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ad')),
                ('surname', models.CharField(max_length=30, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=40, verbose_name='Parol')),
                ('adress', models.CharField(max_length=100, verbose_name='Unvan')),
                ('zipp', models.CharField(max_length=30, verbose_name='ZIP')),
                ('tel', models.CharField(max_length=35, verbose_name='Tel')),
                ('mob', models.CharField(max_length=50, verbose_name='Mob')),
                ('fax', models.CharField(max_length=30, verbose_name='Fax')),
                ('wep', models.CharField(max_length=30, verbose_name='Wep')),
                ('borndate', models.CharField(max_length=30, verbose_name='Dogum Tarixi')),
                ('ixtisas', models.CharField(max_length=30, verbose_name='Ixtisas')),
                ('verzife', models.CharField(max_length=30, verbose_name='Vezife')),
                ('elmiderece', models.CharField(max_length=30, verbose_name='Elmi Derece')),
                ('isYeri', models.CharField(max_length=30, verbose_name='Is Yeri')),
                ('mezunOlmaTarixi', models.CharField(max_length=30, verbose_name='Mezun Oldugu Tarix')),
                ('mezunOlduquYer', models.CharField(max_length=30, verbose_name='Mezun Olduqu Yer')),
                ('fakulte', models.CharField(max_length=30, verbose_name='Fakulte')),
            ],
        ),
    ]
